// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5jGhS8DnDjseoDXvJkUgAwwL6sG6joc',
    appId: '1:571358755927:web:5c9a8ceefa3e70426df712',
    messagingSenderId: '571358755927',
    projectId: 'jay-bhole-goshala-samiti',
    authDomain: 'jay-bhole-goshala-samiti.firebaseapp.com',
    storageBucket: 'jay-bhole-goshala-samiti.firebasestorage.app',
    measurementId: 'G-7965MMN9BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIelWz5iRYlK53MuZGidbBgmPrLnkzKpM',
    appId: '1:571358755927:android:6bf13ad0ce252aa66df712',
    messagingSenderId: '571358755927',
    projectId: 'jay-bhole-goshala-samiti',
    storageBucket: 'jay-bhole-goshala-samiti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQe5aCQr5bsQUDJJBonsivkDd_GjMA4Gs',
    appId: '1:571358755927:ios:0eb34640f58a37ca6df712',
    messagingSenderId: '571358755927',
    projectId: 'jay-bhole-goshala-samiti',
    storageBucket: 'jay-bhole-goshala-samiti.firebasestorage.app',
    iosBundleId: 'com.example.jayBholeGoshala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQe5aCQr5bsQUDJJBonsivkDd_GjMA4Gs',
    appId: '1:571358755927:ios:0eb34640f58a37ca6df712',
    messagingSenderId: '571358755927',
    projectId: 'jay-bhole-goshala-samiti',
    storageBucket: 'jay-bhole-goshala-samiti.firebasestorage.app',
    iosBundleId: 'com.example.jayBholeGoshala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX5jGhS8DnDjseoDXvJkUgAwwL6sG6joc',
    appId: '1:571358755927:web:122f789c399aad396df712',
    messagingSenderId: '571358755927',
    projectId: 'jay-bhole-goshala-samiti',
    authDomain: 'jay-bhole-goshala-samiti.firebaseapp.com',
    storageBucket: 'jay-bhole-goshala-samiti.firebasestorage.app',
    measurementId: 'G-M1RX3GSR0B',
  );

}